title: awesome-languages
description: 'This is a course about awesome languages. '
template:
  repo: awesome-languages-template
  name: awesome-languages
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    link: '{{ repoUrl }}/issues/1'

    # triggers the step
    event: issues.assigned # github webhooks, api docs

    # as a result of the trigger
    actions: # come from the LL docs
      - type: closeIssue
        issue: 1