title: awesome-languages
description: 'This is a course about awesome languages. '
template:
  repo: awesome-languages-template
  name: awesome-languages
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: closeIssue
